### ISSUE TITLE
Unable to brew install avr-libc from weareleka/avr tap

### ISSUE THREAD

**Issue by rajatdeshpande** [WeAreLeka/homebrew-avr#4]
I am on osx yosemite 10.10.3
checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
checking for version 0.12 of ISL... no
configure: error: Unable to find a usable ISL.  See config.log for details.

i have tried installing both isl 0.11 and 0.12 but get the same error message

**Comment by ladislas** [comment]
Hi @rajatdeshpande, this has already been discussed in #2 and #3.

WeAreLeka/homebrew-avr will be deprecated soon in favor to this one where we will continue the development: https://github.com/osx-cross/homebrew-avr
