### ISSUE TITLE
Sha256 missmatch

### ISSUE THREAD

**Issue by oprema** [WeAreLeka/homebrew-avr#5]
I get the following error when installing

==> Downloading http://gnu.cardse.net/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/avr-gcc-4.9.2.tar.bz2
Error: SHA256 mismatch
Expected: 2020c98295856aa13fda0f2f3a4794490757fc24bcca918d52cc8b4917b972dd
Actual: aa8484d4265325cb6b7a9c582bdd50e938dfbb6fc1c56b61a4e898561afefd08
Archive: /Library/Caches/Homebrew/avr-gcc-4.9.2.tar.bz2

Any idea why that is?

**Comment by ladislas** [comment]
I'll take a look at it.


In the meantime, you can use osx-cross formula.
-- 
---

This e-mail and any attached files may contain confidential information 
which is intended exclusively for the recipient. If you are not the 
specified recipient, you should delete this e-mail from your system 
immediately, and inform the sender without delay. Reading, distributing, 
copying, or any other unauthorized use of this e-mail and its attached 
files is strictly forbidden. Thank you for your comprehension.

Cet e-mail et ses éventuelles pièces jointes peuvent contenir des 
informations confidentielles, lesquelles sont envoyées à l’intention 
exclusive de son destinataire. Si vous n’êtes pas le destinataire auquel 
est envoyé cet e-mail, vous devez immédiatement l’effacer de votre système 
et avertir son expéditeur. Toute lecture, distribution, copie ou autre 
utilisation de cet e-mail et de ses éventuelles pièces jointes est 
strictement interdite. Merci.

**Comment by ladislas** [comment]
@oprema yep, you should use https://github.com/osx-cross/homebrew-avr

it is based on our work, and all the development is done there :)

**Comment by oprema** [comment]
Thanks anyway. Have a nice day.
