### ISSUE TITLE
ISL not found

### ISSUE THREAD

**Issue by asllop** [WeAreLeka/homebrew-avr#6]
When configuring avr-gcc, fails trying to find ISL due to it's looking for versions 0.10, 0.11 and 0.12, but the one that is automatically installed is 0.14. I solved it installing ISL 0.12 and manually relinking from /usr/local/opt/isl to isl012 (at /usr/local/Cellar/isl012/0.12.2).

**Comment by ladislas** [comment]
See #3 & #4
